

/*
Esta es la base de datos de los coches que tenemos en nuestra empresa.
Tambien aparecen algunas caracteristicas importates del coche así como del propio precio.
*/

db.Coches.insertMany

[{
  "codcoche":"28as",
  "id_coche": 1,
  "marca_coche": "Suzuki",
  "modelo": "X-90",
  "color": "Amarillo",
  "oferta": true,
  "stock_nuevo": 16,
  "stock_segunda_mano": 4,
  "precio_sin_iva": 63100,
  "precio_extras": 6078,
  "precio_2mano_sin_iva": 8237,
  "garantia_extendida_precio": 4699
}, {
  "codcoche":"29as",
  "id_coche": 2,
  "marca_coche": "Volkswagen",
  "modelo": "Jetta",
  "color": "Turquesa",
  "oferta": true,
  "stock_nuevo": 14,
  "stock_segunda_mano": 10,
  "precio_sin_iva": 30012,
  "precio_extras": 23588,
  "precio_2mano_sin_iva": 5067,
  "garantia_extendida_precio": 4191
}, {
  "codcoche":"30as",
  "id_coche": 3,
  "marca_coche": "Toyota",
  "modelo": "Tacoma",
  "color": "Morado",
  "oferta": false,
  "stock_nuevo": 9,
  "stock_segunda_mano": 4,
  "precio_sin_iva": 70495,
  "precio_extras": 48350,
  "precio_2mano_sin_iva": 4455,
  "garantia_extendida_precio": 2619
}, {
  "codcoche":"31as",
  "id_coche": 4,
  "marca_coche": "Hyundai",
  "modelo": "XG350",
  "color": "Caqui",
  "oferta": false,
  "stock_nuevo": 17,
  "stock_segunda_mano": 9,
  "precio_sin_iva": 69007,
  "precio_extras": 2929,
  "precio_2mano_sin_iva": 2491,
  "garantia_extendida_precio": 4847
}, {
  "codcoche":"32as",
  "id_coche": 5,
  "marca_coche": "Mazda",
  "modelo": "MPV",
  "color": "Verde Turquesa",
  "oferta": true,
  "stock_nuevo": 5,
  "stock_segunda_mano": 1,
  "precio_sin_iva": 29246,
  "precio_extras": 2931,
  "precio_2mano_sin_iva": 3485,
  "garantia_extendida_precio": 3189
}, {
  "codcoche":"33as",
  "id_coche": 6,
  "marca_coche": "Volvo",
  "modelo": "S90",
  "color": "Turquesa",
  "oferta": false,
  "stock_nuevo": 7,
  "stock_segunda_mano": 10,
  "precio_sin_iva": 61165,
  "precio_extras": 10930,
  "precio_2mano_sin_iva": 1656,
  "garantia_extendida_precio": 2725
}, {
  "codcoche":"34as",
  "id_coche": 7,
  "marca_coche": "Land Rover",
  "modelo": "Range Rover",
  "color": "Verde Turquesa",
  "oferta": false,
  "stock_nuevo": 3,
  "stock_segunda_mano": 5,
  "precio_sin_iva": 40129,
  "precio_extras": 45779,
  "precio_2mano_sin_iva": 9906,
  "garantia_extendida_precio": 2444
}, {
  "codcoche":"35as",
  "id_coche": 8,
  "marca_coche": "Mazda",
  "modelo": "B2000",
  "color": "Morado",
  "oferta": false,
  "stock_nuevo": 19,
  "stock_segunda_mano": 10,
  "precio_sin_iva": 50943,
  "precio_extras": 17912,
  "precio_2mano_sin_iva": 7899,
  "garantia_extendida_precio": 1119
}, {
  "codcoche":"36as",
  "id_coche": 9,
  "marca_coche": "Cadillac",
  "modelo": "Escalade EXT",
  "color": "Morado",
  "oferta": false,
  "stock_nuevo": 8,
  "stock_segunda_mano": 8,
  "precio_sin_iva": 60349,
  "precio_extras": 2408,
  "precio_2mano_sin_iva": 8798,
  "garantia_extendida_precio": 3411
}, {
  "codcoche":"37as",
  "id_coche": 10,
  "marca_coche": "Hyundai",
  "modelo": "Tiburon",
  "color": "Caqui",
  "oferta": true,
  "stock_nuevo": 4,
  "stock_segunda_mano": 7,
  "precio_sin_iva": 32521,
  "precio_extras": 12626,
  "precio_2mano_sin_iva": 2662,
  "garantia_extendida_precio": 3362
}, {
  "codcoche":"38as",
  "id_coche": 11,
  "marca_coche": "Mitsubishi",
  "modelo": "RVR",
  "color": "Morado",
  "oferta": true,
  "stock_nuevo": 11,
  "stock_segunda_mano": 4,
  "precio_sin_iva": 49419,
  "precio_extras": 10692,
  "precio_2mano_sin_iva": 5998,
  "garantia_extendida_precio": 1072
}, {
  "codcoche":"39as",
  "id_coche": 12,
  "marca_coche": "Kia",
  "modelo": "Sorento",
  "color": "Verde Turquesa",
  "oferta": false,
  "stock_nuevo": 16,
  "stock_segunda_mano": 8,
  "precio_sin_iva": 20448,
  "precio_extras": 40925,
  "precio_2mano_sin_iva": 8618,
  "garantia_extendida_precio": 2498
}, {
  "codcoche":"40as",
  "id_coche": 13,
  "marca_coche": "Buick",
  "modelo": "LaCrosse",
  "color": "Turquesa",
  "oferta": false,
  "stock_nuevo": 4,
  "stock_segunda_mano": 5,
  "precio_sin_iva": 28702,
  "precio_extras": 39087,
  "precio_2mano_sin_iva": 5931,
  "garantia_extendida_precio": 2977
}, {
  "codcoche":"41as",
  "id_coche": 14,
  "marca_coche": "Buick",
  "modelo": "LeSabre",
  "color": "Rojo Torino",
  "oferta": false,
  "stock_nuevo": 7,
  "stock_segunda_mano": 7,
  "precio_sin_iva": 41854,
  "precio_extras": 31652,
  "precio_2mano_sin_iva": 1736,
  "garantia_extendida_precio": 4997
}, {
  "codcoche":"42as",
  "id_coche": 15,
  "marca_coche": "Mercedes-Benz",
  "modelo": "300SL",
  "color": "Rojo",
  "oferta": true,
  "stock_nuevo": 5,
  "stock_segunda_mano": 8,
  "precio_sin_iva": 42133,
  "precio_extras": 4047,
  "precio_2mano_sin_iva": 8223,
  "garantia_extendida_precio": 1074
}, {
  "codcoche":"43as",
  "id_coche": 16,
  "marca_coche": "Suzuki",
  "modelo": "Swift",
  "color": "Granate",
  "oferta": false,
  "stock_nuevo": 20,
  "stock_segunda_mano": 9,
  "precio_sin_iva": 70990,
  "precio_extras": 38264,
  "precio_2mano_sin_iva": 5795,
  "garantia_extendida_precio": 2666
}, {
  "codcoche":"44as",
  "id_coche": 17,
  "marca_coche": "Mitsubishi",
  "modelo": "Outlander",
  "color": "Blanco escarcha",
  "oferta": false,
  "stock_nuevo": 14,
  "stock_segunda_mano": 8,
  "precio_sin_iva": 44625,
  "precio_extras": 2148,
  "precio_2mano_sin_iva": 4224,
  "garantia_extendida_precio": 2998
}, {
  "codcoche":"45as",
  "id_coche": 18,
  "marca_coche": "BMW",
  "modelo": "M3",
  "color": "Verde",
  "oferta": false,
  "stock_nuevo": 18,
  "stock_segunda_mano": 8,
  "precio_sin_iva": 86342,
  "precio_extras": 16682,
  "precio_2mano_sin_iva": 7435,
  "garantia_extendida_precio": 1026
}, {
  "codcoche":"46as",
  "id_coche": 19,
  "marca_coche": "Mercedes-Benz",
  "modelo": "CLS-Class",
  "color": "Morado",
  "oferta": false,
  "stock_nuevo": 5,
  "stock_segunda_mano": 6,
  "precio_sin_iva": 32668,
  "precio_extras": 12724,
  "precio_2mano_sin_iva": 3071,
  "garantia_extendida_precio": 1815
}, {
  "codcoche":"47as",
  "id_coche": 20,
  "marca_coche": "Dodge",
  "modelo": "Stratus",
  "color": "Fucsia",
  "oferta": false,
  "stock_nuevo": 14,
  "stock_segunda_mano": 9,
  "precio_sin_iva": 67523,
  "precio_extras": 26107,
  "precio_2mano_sin_iva": 5795,
  "garantia_extendida_precio": 1570
}, {
  "codcoche":"48as",
  "id_coche": 21,
  "marca_coche": "Nissan",
  "modelo": "350Z",
  "color": "Fucsia",
  "oferta": true,
  "stock_nuevo": 13,
  "stock_segunda_mano": 2,
  "precio_sin_iva": 43516,
  "precio_extras": 10646,
  "precio_2mano_sin_iva": 9474,
  "garantia_extendida_precio": 3328
}, {
  "codcoche":"49as",
  "id_coche": 22,
  "marca_coche": "Volvo",
  "modelo": "XC90",
  "color": "Marron Caoba",
  "oferta": true,
  "stock_nuevo": 16,
  "stock_segunda_mano": 8,
  "precio_sin_iva": 10610,
  "precio_extras": 8189,
  "precio_2mano_sin_iva": 7987,
  "garantia_extendida_precio": 1785
}, {
  "codcoche":"50as",
  "id_coche": 23,
  "marca_coche": "Mitsubishi",
  "modelo": "Mirage",
  "color": "Naranja amanecer",
  "oferta": true,
  "stock_nuevo": 10,
  "stock_segunda_mano": 8,
  "precio_sin_iva": 24629,
  "precio_extras": 34258,
  "precio_2mano_sin_iva": 2292,
  "garantia_extendida_precio": 4318
}, {
  "codcoche":"51as",
  "id_coche": 24,
  "marca_coche": "Suzuki",
  "modelo": "SX4",
  "color": "Rosa",
  "oferta": false,
  "stock_nuevo": 18,
  "stock_segunda_mano": 10,
  "precio_sin_iva": 70721,
  "precio_extras": 27520,
  "precio_2mano_sin_iva": 7311,
  "garantia_extendida_precio": 3519
}, {
  "codcoche":"52as",
  "id_coche": 25,
  "marca_coche": "Honda",
  "modelo": "Passport",
  "color": "Naranja",
  "oferta": false,
  "stock_nuevo": 9,
  "stock_segunda_mano": 8,
  "precio_sin_iva": 17293,
  "precio_extras": 46577,
  "precio_2mano_sin_iva": 4478,
  "garantia_extendida_precio": 3087
}, {
  "codcoche":"53as",
  "id_coche": 26,
  "marca_coche": "Mercedes-Benz",
  "modelo": "W201",
  "color": "Negro Puro",
  "oferta": true,
  "stock_nuevo": 11,
  "stock_segunda_mano": 6,
  "precio_sin_iva": 9449,
  "precio_extras": 21707,
  "precio_2mano_sin_iva": 5034,
  "garantia_extendida_precio": 3260
}, {
  "codcoche":"54as",
  "id_coche": 27,
  "marca_coche": "Dodge",
  "modelo": "Caliber",
  "color": "Verde Turquesa",
  "oferta": false,
  "stock_nuevo": 10,
  "stock_segunda_mano": 2,
  "precio_sin_iva": 25731,
  "precio_extras": 29254,
  "precio_2mano_sin_iva": 1828,
  "garantia_extendida_precio": 4014
}, {
  "codcoche":"55as",
  "id_coche": 28,
  "marca_coche": "Cadillac",
  "modelo": "CTS-V",
  "color": "Turquesa",
  "oferta": false,
  "stock_nuevo": 5,
  "stock_segunda_mano": 3,
  "precio_sin_iva": 57379,
  "precio_extras": 4755,
  "precio_2mano_sin_iva": 9611,
  "garantia_extendida_precio": 2587
}, {
  "codcoche":"56as",
  "id_coche": 29,
  "marca_coche": "Cadillac",
  "modelo": "Catera",
  "color": "Negro Puro",
  "oferta": false,
  "stock_nuevo": 10,
  "stock_segunda_mano": 9,
  "precio_sin_iva": 62192,
  "precio_extras": 19457,
  "precio_2mano_sin_iva": 6904,
  "garantia_extendida_precio": 4581
}, {
  "codcoche":"57as",
  "id_coche": 30,
  "marca_coche": "Audi",
  "modelo": "5000S",
  "color": "Amarillo",
  "oferta": false,
  "stock_nuevo": 7,
  "stock_segunda_mano": 10,
  "precio_sin_iva": 72092,
  "precio_extras": 16539,
  "precio_2mano_sin_iva": 9333,
  "garantia_extendida_precio": 3662
}, {
  "codcoche":"58as",
  "id_coche": 31,
  "marca_coche": "Mitsubishi",
  "modelo": "Cordia",
  "color": "Rojo",
  "oferta": false,
  "stock_nuevo": 11,
  "stock_segunda_mano": 8,
  "precio_sin_iva": 71175,
  "precio_extras": 11241,
  "precio_2mano_sin_iva": 3764,
  "garantia_extendida_precio": 2955
}, {
  "codcoche":"59as",
  "id_coche": 32,
  "marca_coche": "Audi",
  "modelo": "TT",
  "color": "Turquesa",
  "oferta": false,
  "stock_nuevo": 15,
  "stock_segunda_mano": 9,
  "precio_sin_iva": 32903,
  "precio_extras": 25533,
  "precio_2mano_sin_iva": 8230,
  "garantia_extendida_precio": 2729
}, {
  "codcoche":"60as",
  "id_coche": 33,
  "marca_coche": "Ford",
  "modelo": "Mustang",
  "color": "Negro Puro",
  "oferta": false,
  "stock_nuevo": 7,
  "stock_segunda_mano": 3,
  "precio_sin_iva": 56630,
  "precio_extras": 42181,
  "precio_2mano_sin_iva": 4767,
  "garantia_extendida_precio": 3205
}, {
  "codcoche":"61as",
  "id_coche": 34,
  "marca_coche": "Chevrolet",
  "modelo": "Silverado 2500",
  "color": "Blanco escarcha",
  "oferta": false,
  "stock_nuevo": 7,
  "stock_segunda_mano": 5,
  "precio_sin_iva": 26108,
  "precio_extras": 27325,
  "precio_2mano_sin_iva": 1688,
  "garantia_extendida_precio": 2066
}, {
  "codcoche":"62as",
  "id_coche": 35,
  "marca_coche": "Buick",
  "modelo": "LeSabre",
  "color": "Negro Puro",
  "oferta": true,
  "stock_nuevo": 19,
  "stock_segunda_mano": 1,
  "precio_sin_iva": 42655,
  "precio_extras": 9932,
  "precio_2mano_sin_iva": 7915,
  "garantia_extendida_precio": 4208
}, {

}]